"""Phase 4A.1 — registry summary, source locations, signal schema, evidence paths."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ionogram_morphology_lab.app.settings_store import DEFAULT_SETTINGS
from ionogram_morphology_lab.features.v2.types import FEATURE_VERSION
from ionogram_morphology_lab.scientific_outputs.formula_registry import (
    formula_summary,
    get_formula,
    load_formula_registry,
    validate_registry_structure,
)
from ionogram_morphology_lab.scientific_outputs.formula_summary import (
    SUMMARY_GROUP_KEYS,
    compute_formula_summary,
)
from ionogram_morphology_lab.scientific_outputs.signal_contracts import (
    load_signal_contracts,
    validate_contract_schema,
)
from ionogram_morphology_lab.rules.engine import RuleEngine
from ionogram_morphology_lab.features.extract import extract_features
from ionogram_morphology_lab.segmentation.trace_interference import segment_frame


ROOT = Path(__file__).resolve().parents[1]


def test_formula_summary_computed_not_hand_copied():
    data = load_formula_registry()
    assert data.get("summary_source") == "computed_from_classification"
    items = data["items"]
    assert data["summary"] == compute_formula_summary(items)
    for key in SUMMARY_GROUP_KEYS:
        assert key in data["summary"]
    # Instrument conversions must NOT sit under exact_physical_formulas
    exact = set(data["summary"]["exact_physical_formulas"])
    assert "HEUR_BIN_TO_MHZ" not in exact
    assert "HEUR_BIN_TO_NOMINAL_HEIGHT" not in exact
    assert "HEUR_BIN_TO_MHZ" in data["summary"]["instrument_specific_procedures"]
    assert exact == {"F001"}
    assert "F002" not in exact
    assert data["summary"]["observational_definitions"] == ["F002"]
    assert "F003" in data["summary"]["instrument_specific_procedures"]
    assert "F004" in data["summary"]["morphology_definitions"]
    counts = {k: len(v) for k, v in data["summary"].items()}
    assert counts["exact_physical_formulas"] == 1
    assert counts["observational_definitions"] == 1
    assert counts["exact_signal_processing_formulas"] == 0
    assert counts["instrument_specific_procedures"] == 3
    assert counts["morphology_definitions"] == 4
    assert counts["project_engineering_heuristics"] == 1
    assert counts["unsupported_or_disabled"] == 3


def test_f004_and_defs_have_precise_source_location():
    for fid in ("F004", "DEF_FREQUENCY_SPREAD", "DEF_RANGE_SPREAD", "DEF_MIXED_SPREAD"):
        item = get_formula(fid)
        loc = item.get("source_location") or {}
        assert any(
            loc.get(k) not in (None, "")
            for k in ("printed_page", "pdf_page", "section", "figure", "table", "equation")
        ), fid
        assert item.get("expression_kind") in {
            "exact_quotation",
            "translated_quotation",
            "close_paraphrase",
            "project_interpretation",
        }
        page = (item.get("exact_page_or_equation") or "").lower()
        assert "operational morphology classes" not in page
        assert "pages unknown" not in page


def test_def_mixed_is_project_interpretation():
    item = get_formula("DEF_MIXED_SPREAD")
    assert item["expression_kind"] == "project_interpretation"
    assert item["exact_source_id"] == "A2_PROTOCOL"
    assert item["validation_status"] != "exact_verified"


def test_signal_contract_schema_no_mixed_shape_notes():
    data = load_signal_contracts()
    errs = validate_contract_schema(data)
    assert not errs, errs
    amp = next(c for c in data["contracts"] if c["variable_name"] == "Amp_all")
    assert "accepted_shapes" in amp
    assert all(isinstance(s, list) for s in amp["accepted_shapes"])
    assert "accepted_shape_variants" not in amp
    assert amp["optional_presence"] is False
    assert isinstance(amp["verification_evidence"], list)


def test_formula_pipeline_and_v2_remain_disabled():
    assert DEFAULT_SETTINGS["analysis"]["scientific_formula_pipeline_enabled"] is False
    assert DEFAULT_SETTINGS["analysis"]["scientific_feature_pipeline_v2_enabled"] is False
    assert FEATURE_VERSION.startswith("iml2-")  # V2 code preserved, not enabled


def test_registry_structure_ok():
    assert not validate_registry_structure()


def test_morphology_unchanged_smoke():
    # Thin synthetic ridge — ensure RuleEngine still runs; no threshold edits in 4A.1
    frame = np.zeros((128, 200), dtype=float)
    frame[40:42, 20:180] = 100
    seg = segment_frame(frame)
    feats = extract_features(frame, seg)
    res = RuleEngine().evaluate(feats.values, quality_status="valid")
    assert res.candidate_morphology is not None


def test_evidence_bundle_layout_when_present():
    ev = ROOT / "workspaces" / "_phase4a_evidence"
    if not (ev / "source_sha256.txt").is_file():
        return  # generated by export script in CI/local verification
    for name in (
        "source_identity.json",
        "frame_0001_identity.json",
        "frame_0421_identity.json",
        "frame_1440_identity.json",
        "frame_0001.npy",
        "frame_0421.npy",
        "frame_1440.npy",
        "mapping_comparison.json",
        "source_sha256.txt",
    ):
        assert (ev / name).is_file(), name
    mapping = (ev / "mapping_comparison.json").read_text(encoding="utf-8")
    assert "extract_frame_consistent" in mapping
    assert "confirmed_same_canonical_extraction" in mapping
