"""Intro panel texts for every main navigation page."""

from __future__ import annotations

from ionogram_morphology_lab.ui.intro_panel import IntroPanel

# page_id -> kwargs for IntroPanel (without i18n/settings)
PAGE_INTROS: dict[str, dict[str, str]] = {
    "projects": dict(
        purpose_en="Create or open a local analysis project that stores runs and decisions.",
        purpose_ru="Создать или открыть локальный проект анализа с запусками и решениями.",
        when_en="Before importing data or continuing unfinished work.",
        when_ru="Перед импортом данных или продолжением незавершённой работы.",
        action_en="Enter a name and create a project, or open an existing workspace.",
        action_ru="Введите имя и создайте проект или откройте существующую область.",
        after_en="The project becomes active on Home and in the status bar.",
        after_ru="Проект станет активным на Главной и в строке состояния.",
        risk_en="Canceling leave you without a project; analysis pages stay blocked.",
        risk_ru="Отмена оставит вас без проекта; страницы анализа останутся недоступны.",
        help_id="project",
    ),
    "import": dict(
        purpose_en="Select MAT files or folders without modifying source archives.",
        purpose_ru="Выбрать MAT-файлы или папки без изменения исходных архивов.",
        when_en="After a project exists and before viewing or analysis.",
        when_ru="После создания проекта и до просмотра или анализа.",
        action_en="Import a file or folder, then review the audit card.",
        action_ru="Импортируйте файл или папку и проверьте карточку аудита.",
        after_en="Active MAT appears on Home; next step is usually the instrument profile.",
        after_ru="Активный MAT появится на Главной; далее обычно профиль прибора.",
        risk_en="Unsupported shapes or empty folders produce clear errors — source stays untouched.",
        risk_ru="Неподдерживаемая форма или пустая папка даст понятную ошибку — источник не меняется.",
        help_id="import",
    ),
    "profile": dict(
        purpose_en="Map matrix dimensions to frames, frequency, and nominal virtual height.",
        purpose_ru="Сопоставить матрицу с кадрами, частотой и номинальной виртуальной высотой.",
        when_en="After import, before cache and Viewer.",
        when_ru="После импорта, до кэша и просмотра.",
        action_en="Load the KFU provisional profile or complete the unknown-MAT wizard.",
        action_ru="Загрузите провизорный профиль KFU или завершите мастер неизвестного MAT.",
        after_en="Profile id is stored on the project; Why? explains provisional status.",
        after_ru="ID профиля сохраняется в проекте; «Почему?» поясняет провизорный статус.",
        risk_en="Wrong profile yields wrong axes — always confirm before scientific claims.",
        risk_ru="Неверный профиль даёт неверные оси — подтвердите до научных выводов.",
        help_id="profiles",
    ),
    "audit": dict(
        purpose_en="Audit variables/shapes and build the derived frame cache.",
        purpose_ru="Проверить переменные/формы и создать производный кэш кадров.",
        when_en="When data is imported and a profile is selected.",
        when_ru="Когда данные импортированы и выбран профиль.",
        action_en="Run audit, then build cache if automatic build did not complete.",
        action_ru="Запустите аудит, затем создайте кэш, если автосборка не завершилась.",
        after_en="Cache status becomes ready; Viewer can open real frames.",
        after_ru="Статус кэша станет ready; просмотрщик откроет реальные кадры.",
        risk_en="Slow disks and huge MAT files take time; cancel is safe; MAT stays read-only.",
        risk_ru="Медленный диск и большие MAT требуют времени; отмена безопасна; MAT только для чтения.",
        help_id="cache",
    ),
    "viewer": dict(
        purpose_en="Inspect real ionogram frames with time mapping and overlays.",
        purpose_ru="Просматривать реальные кадры ионограмм с привязкой времени и оверлеями.",
        when_en="After cache is ready.",
        when_ru="После готовности кэша.",
        action_en="Open the first frame, step through time, optionally build a contact sheet.",
        action_ru="Откройте первый кадр, листайте время, при необходимости создайте контактный лист.",
        after_en="Current frame updates on Home; you can select an interval for analysis.",
        after_ru="Текущий кадр обновится на Главной; можно выбрать интервал для анализа.",
        risk_en="Nominal virtual height is not true height — see Why?",
        risk_ru="Номинальная виртуальная высота — не истинная; см. «Почему?»",
        help_id="viewer",
    ),
    "batch": dict(
        purpose_en="Choose exactly which ionograms to analyse, then review a plain-language confirmation before starting.",
        purpose_ru="Выберите, какие ионограммы анализировать, затем проверьте понятное подтверждение перед запуском.",
        when_en="After Viewer and cache are ready. Example: analyse 05:00–07:00 every 10 minutes.",
        when_ru="После готовности просмотра и кэша. Пример: анализировать 05:00–07:00 каждые 10 минут.",
        action_en="Pick current frame, range, time range, every N minutes, entire file, or a custom list; choose preset and stages.",
        action_ru="Выберите текущий кадр, диапазон, время, каждые N минут, весь файл или список; задайте предустановку и этапы.",
        after_en="Results retain selected frames, pipeline, rules, and output location. This does not prove a physical mechanism.",
        after_ru="Результаты сохраняют выбранные кадры, конвейер, правила и папку вывода. Это не доказывает физический механизм.",
        risk_en="Common mistake: treating a candidate category as a confirmed measurement. Use Results → Evidence before reporting.",
        risk_ru="Типичная ошибка: считать кандидатную категорию подтверждённым измерением. Перед отчётом откройте Результаты → Доказательства.",
        help_id="batch_run",
    ),
    "results": dict(
        purpose_en="Inspect candidate layer, morphology, ambiguity, quality, and the evidence that produced each result.",
        purpose_ru="Проверьте кандидатные слой, морфологию, неоднозначность, качество и доказательства каждого результата.",
        when_en="After an analysis run completes.",
        when_ru="После завершения анализа.",
        action_en="Review the translated result card, evidence, alternatives, and limitations; technical tokens are kept separately.",
        action_ru="Проверьте переведённую карточку, доказательства, альтернативы и ограничения; технические токены показаны отдельно.",
        after_en="Accepted decisions feed reports and reproducibility manifests.",
        after_ru="Принятые решения попадают в отчёты и манифесты воспроизводимости.",
        risk_en="A morphology example is not proof of a mechanism or a confirmed physical measurement. Follow the Results help link for examples.",
        risk_ru="Пример морфологии не доказывает механизм и не является подтверждённым физическим измерением. Примеры — по ссылке справки Результатов.",
        help_id="results",
    ),
    "raw_signals": dict(
        purpose_en="Inspect the numeric MAT frame that underlies the rendered ionogram.",
        purpose_ru="Просмотреть числовой кадр MAT, из которого строится ионограмма.",
        when_en="In Expert/Research mode when verifying axes, contracts, or exports.",
        when_ru="В режиме Эксперт/Исследование при проверке осей, контрактов или экспорта.",
        action_en="Refresh stats for the current frame; optionally export a read-only diagnostic package.",
        action_ru="Обновите статистику текущего кадра; при необходимости экспортируйте диагностический пакет.",
        after_en="Use contract IDs and hashes in reports — never treat PNG as the primary scientific input.",
        after_ru="Используйте ID контрактов и хеши в отчётах — не считайте PNG первичным научным входом.",
        risk_en="Phase data may be present but unverified; automatic phase rules stay disabled.",
        risk_ru="Фазовые данные могут присутствовать, но быть неподтверждёнными; автоправила фазы отключены.",
        help_id="variables",
    ),
    "feature_diagnostics": dict(
        purpose_en="Inspect trace and geometry diagnostics from Feature Pipeline V2 in shadow mode.",
        purpose_ru="Просмотреть диагностику следа и геометрии Feature Pipeline V2 в теневом режиме.",
        when_en="In Expert mode when auditing geometric measurements without changing classification.",
        when_ru="В режиме Эксперт при аудите геометрических измерений без изменения классификации.",
        action_en="Load a frame, then explicitly run V2 shadow analysis or open cached diagnostics; layers load on demand.",
        action_ru="Загрузите кадр, затем явно запустите теневой анализ V2 или откройте кэш; слои загружаются по запросу.",
        after_en="V2 outputs remain experimental and do not feed the current RuleEngine decision.",
        after_ru="Выходы V2 остаются экспериментальными и не участвуют в текущем решении RuleEngine.",
        risk_en="Measurements are not morphology classes; do not treat elevated width as frequency/range/mixed spread.",
        risk_ru="Измерения — не классы морфологии; не считайте повышенную ширину частотным/высотным/смешанным рассеянием.",
        help_id="features",
    ),
    "matlab": dict(
        purpose_en="Edit and run MATLAB teaching/research methods in isolation.",
        purpose_ru="Редактировать и запускать MATLAB-методы в изоляции.",
        when_en="When a MATLAB/Octave backend is available, or to browse built-in methods.",
        when_ru="Когда доступен бэкенд MATLAB/Octave, или для просмотра встроенных методов.",
        action_en="Select a method, run on the current frame, inspect diary and outputs.",
        action_ru="Выберите метод, запустите на текущем кадре, проверьте дневник и выходы.",
        after_en="Outputs attach to the run workspace; source MAT stays read-only.",
        after_ru="Выходы попадают в рабочую область запуска; исходный MAT только для чтения.",
        risk_en="Missing backend shows a clear message; script errors do not crash the GUI.",
        risk_ru="Отсутствие бэкенда даёт понятное сообщение; ошибка скрипта не роняет GUI.",
        help_id="matlab_studio",
    ),
    "settings": dict(
        purpose_en="Configure language, analysis mode, performance, MATLAB backend, and privacy.",
        purpose_ru="Настроить язык, режим анализа, производительность, MATLAB и конфиденциальность.",
        when_en="At first launch and whenever environment constraints change.",
        when_ru="При первом запуске и при изменении условий среды.",
        action_en="Change only what you understand; save; note UX mode vs analysis mode.",
        action_ru="Меняйте понятные пункты; сохраните; различайте UX-режим и режим анализа.",
        after_en="Settings persist locally; telemetry remains disabled by default.",
        after_ru="Настройки сохраняются локально; телеметрия по умолчанию выключена.",
        risk_en="Wrong analysis mode can hide experimental rules in Scientific Strict.",
        risk_ru="Неверный режим анализа может скрыть экспериментальные правила в Scientific Strict.",
        help_id="ux_modes",
    ),
    "help": dict(
        purpose_en="Search bilingual Help topics, including synonyms.",
        purpose_ru="Искать двуязычные разделы справки, включая синонимы.",
        when_en="Whenever a control or workflow step is unclear.",
        when_ru="Когда непонятен элемент управления или шаг процесса.",
        action_en="Type a query (e.g. своё правило, медленно, O/X) and open a topic.",
        action_ru="Введите запрос (например «своё правило», «медленно», «O/X») и откройте тему.",
        after_en="Restore dismissed page intros from Help if needed.",
        after_ru="При необходимости восстановите скрытые введения страниц из Справки.",
        risk_en="Missing translation keys fall back safely; report gaps to maintainers.",
        risk_ru="Отсутствующие ключи локализации обрабатываются безопасно.",
        help_id="quick_start",
    ),
    "reports": dict(
        purpose_en="Export bilingual reproducible reports with manifests and hashes.",
        purpose_ru="Экспортировать двуязычные воспроизводимые отчёты с манифестами и хешами.",
        when_en="After results (and optional expert decisions) are ready.",
        when_ru="После готовности результатов (и при необходимости решений эксперта).",
        action_en="Choose formats/language and export to a writable folder.",
        action_ru="Выберите форматы/язык и экспортируйте в доступную для записи папку.",
        after_en="HTML/CSV/JSON and reproducibility files are written; HTML escapes user text.",
        after_ru="Пишутся HTML/CSV/JSON и файлы воспроизводимости; HTML экранирует текст.",
        risk_en="Canceling the dialog creates no files; disk-full errors are reported clearly.",
        risk_ru="Отмена диалога не создаёт файлов; переполнение диска сообщается явно.",
        help_id="export",
    ),
}


def attach_intro(page_id: str, layout, i18n, settings) -> IntroPanel | None:
    spec = PAGE_INTROS.get(page_id)
    if not spec or settings is None:
        return None
    panel = IntroPanel(page_id, i18n, settings, **spec)
    layout.insertWidget(1, panel)  # after title
    return panel
