"""Feature registry — each feature has definition, units, limitations, citation class."""

from __future__ import annotations

from typing import Any

FEATURE_REGISTRY: dict[str, dict[str, Any]] = {
    # 16.1 Trace visibility
    "trace_pixel_fraction": {
        "group": "trace_visibility",
        "definition": "fraction of pixels in trace_mask",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Overall visible trace occupancy",
        "citation_class": "engineering_image_analysis",
        "limitations": "Depends on segmentation threshold",
    },
    "trace_frequency_coverage": {
        "group": "trace_visibility",
        "definition": "fraction of frequency columns with any trace pixel",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Frequency-axis coverage of candidate trace",
        "citation_class": "engineering_image_analysis",
        "limitations": "Not a critical-frequency measurement",
    },
    "trace_virtual_height_coverage": {
        "group": "trace_visibility",
        "definition": "fraction of range rows with any trace pixel",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Nominal virtual-height coverage",
        "citation_class": "engineering_image_analysis",
        "limitations": "Nominal height axis only",
    },
    "largest_component_fraction": {
        "group": "trace_visibility",
        "definition": "size of largest CC / total trace pixels",
        "units": "dimensionless",
        "input": "component_map",
        "interpretation": "Dominance of primary connected structure",
        "citation_class": "engineering_image_analysis",
        "limitations": "Connectivity depends on threshold",
    },
    "component_count": {
        "group": "trace_visibility",
        "definition": "number of connected components in trace_mask",
        "units": "count",
        "input": "component_map",
        "interpretation": "Fragmentation of candidate trace",
        "citation_class": "engineering_image_analysis",
        "limitations": "Sensitive to noise speckles",
    },
    "skeleton_length": {
        "group": "trace_visibility",
        "definition": "count of skeleton pixels",
        "units": "pixels",
        "input": "skeleton",
        "interpretation": "Approximate trace length",
        "citation_class": "engineering_image_analysis",
        "limitations": "Skeletonization artifact-prone",
    },
    "continuity_score": {
        "group": "trace_visibility",
        "definition": "1 - gap_fraction along frequency projection",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Along-frequency continuity",
        "citation_class": "engineering_image_analysis",
        "limitations": "Not physical continuity proof",
    },
    "gap_fraction": {
        "group": "trace_visibility",
        "definition": "fraction of gaps in frequency coverage span",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Interruptions along frequency",
        "citation_class": "engineering_image_analysis",
        "limitations": "Heuristic",
    },
    "local_slope_distribution_std": {
        "group": "trace_visibility",
        "definition": "std of local dH/df along ridge",
        "units": "bins/bin",
        "input": "ridge_map",
        "interpretation": "Trace slope variability",
        "citation_class": "engineering_image_analysis",
        "limitations": "Index space, not physical units unless calibrated",
    },
    # 16.2 Frequency-spread-compatible
    "median_horizontal_width": {
        "group": "frequency_spread",
        "definition": "median horizontal width of trace per row",
        "units": "frequency_bins",
        "input": "trace_mask",
        "interpretation": "Frequency-spread-compatible diffuseness",
        "citation_class": "engineering_image_analysis",
        "limitations": "Compatible feature only — not confirmed Spread-F",
        "source_claim": "C03",
    },
    "max_horizontal_width": {
        "group": "frequency_spread",
        "definition": "maximum horizontal width of trace per row",
        "units": "frequency_bins",
        "input": "trace_mask",
        "interpretation": "Peak horizontal broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Compatible feature only",
    },
    "horizontal_width_variability": {
        "group": "frequency_spread",
        "definition": "IQR of horizontal widths",
        "units": "frequency_bins",
        "input": "trace_mask",
        "interpretation": "Variability of horizontal broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Compatible feature only",
    },
    "frequency_projection_entropy": {
        "group": "frequency_spread",
        "definition": "Shannon entropy of column-sum projection",
        "units": "nats",
        "input": "trace_mask",
        "interpretation": "Frequency-axis diffuseness",
        "citation_class": "engineering_image_analysis",
        "limitations": "Methodological entropy, not ionospheric law",
    },
    "horizontal_broadening_persistence": {
        "group": "frequency_spread",
        "definition": "fraction of rows with width > threshold",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Persistence of horizontal broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Threshold is development_calibration",
    },
    # 16.3 Range-spread-compatible
    "median_vertical_width": {
        "group": "range_spread",
        "definition": "median vertical width of trace per column",
        "units": "range_bins",
        "input": "trace_mask",
        "interpretation": "Range/virtual-height spread-compatible diffuseness",
        "citation_class": "engineering_image_analysis",
        "limitations": "Nominal height; not true height",
        "source_claim": "C01",
    },
    "max_vertical_width": {
        "group": "range_spread",
        "definition": "maximum vertical width of trace per column",
        "units": "range_bins",
        "input": "trace_mask",
        "interpretation": "Peak vertical broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Compatible feature only",
    },
    "vertical_width_variability": {
        "group": "range_spread",
        "definition": "IQR of vertical widths",
        "units": "range_bins",
        "input": "trace_mask",
        "interpretation": "Variability of vertical broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Compatible feature only",
    },
    "vertical_projection_entropy": {
        "group": "range_spread",
        "definition": "Shannon entropy of row-sum projection",
        "units": "nats",
        "input": "trace_mask",
        "interpretation": "Virtual-height diffuseness",
        "citation_class": "engineering_image_analysis",
        "limitations": "Methodological entropy",
    },
    "vertical_broadening_persistence": {
        "group": "range_spread",
        "definition": "fraction of columns with width > threshold",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Persistence of vertical broadening",
        "citation_class": "engineering_image_analysis",
        "limitations": "Threshold is development_calibration",
    },
    # 16.4 Mixed
    "mixed_width_score": {
        "group": "mixed",
        "definition": "geometric mean of normalized horiz/vert median widths",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Simultaneous horizontal and vertical width score",
        "citation_class": "engineering_image_analysis",
        "limitations": "Candidate mixed morphology only",
    },
    "mixed_coverage": {
        "group": "mixed",
        "definition": "fraction of trace regions exceeding both width criteria",
        "units": "dimensionless",
        "input": "trace_mask",
        "interpretation": "Mixed coverage",
        "citation_class": "engineering_image_analysis",
        "limitations": "Development thresholds",
    },
    "orientation_entropy": {
        "group": "mixed",
        "definition": "entropy of local orientation histogram on ridge",
        "units": "nats",
        "input": "ridge_map",
        "interpretation": "Orientation diversity",
        "citation_class": "engineering_image_analysis",
        "limitations": "Heuristic",
    },
    # 16.5 O/X ambiguity — never auto-claim O/X
    "parallel_branch_count": {
        "group": "ox_ambiguity",
        "definition": "estimated parallel ridge branches",
        "units": "count",
        "input": "ridge_map",
        "interpretation": "Possible multi-branch structure",
        "citation_class": "engineering_image_analysis",
        "limitations": "Do not claim O/X from branch count alone (C02)",
        "source_claim": "C02",
    },
    "branch_separation": {
        "group": "ox_ambiguity",
        "definition": "median separation between top-2 ridges",
        "units": "range_bins",
        "input": "ridge_map",
        "interpretation": "Branch separation",
        "citation_class": "engineering_image_analysis",
        "limitations": "Not proven O/X",
    },
    "possible_ox_compatibility": {
        "group": "ox_ambiguity",
        "definition": "heuristic score in [0,1] for clean double branch",
        "units": "dimensionless",
        "input": "ridge_map",
        "interpretation": "Possible O/X compatibility (not confirmation)",
        "citation_class": "engineering_image_analysis",
        "limitations": "Polarimetry unavailable in Amp_all archive",
        "source_claim": "C02",
    },
    # 16.6 Interference
    "vertical_stripe_density": {
        "group": "interference",
        "definition": "fraction of columns flagged as interference",
        "units": "dimensionless",
        "input": "interference_mask",
        "interpretation": "Vertical interference density",
        "citation_class": "engineering_image_analysis",
        "limitations": "Heuristic",
    },
    "full_height_stripe_count": {
        "group": "interference",
        "definition": "columns with interference covering >=55% height",
        "units": "count",
        "input": "interference_mask",
        "interpretation": "Full-height stripe count",
        "citation_class": "engineering_image_analysis",
        "limitations": "Heuristic",
    },
    "saturated_fraction": {
        "group": "interference",
        "definition": "fraction of pixels near amplitude max",
        "units": "dimensionless",
        "input": "raw_frame",
        "interpretation": "Saturation",
        "citation_class": "engineering_image_analysis",
        "limitations": "Depends on amplitude scale",
    },
    "interference_dominance": {
        "group": "interference",
        "definition": "interference pixels / (trace+interference)",
        "units": "dimensionless",
        "input": "masks",
        "interpretation": "Interference dominance",
        "citation_class": "engineering_image_analysis",
        "limitations": "Heuristic",
    },
    # 16.7 Temporal — computed when sequence provided
    "temporal_persistence": {
        "group": "temporal",
        "definition": "mean IoU of consecutive trace masks",
        "units": "dimensionless",
        "input": "sequence_masks",
        "interpretation": "Temporal persistence",
        "citation_class": "engineering_image_analysis",
        "limitations": "Sequence-only metric; physical-context plugins are not inputs",
    },
    "neighboring_frame_agreement": {
        "group": "temporal",
        "definition": "agreement of candidate morphology across neighbors",
        "units": "dimensionless",
        "input": "sequence_labels",
        "interpretation": "Neighbor agreement",
        "citation_class": "engineering_image_analysis",
        "limitations": "Requires prior per-frame proposals",
    },
}


def list_features() -> list[str]:
    return sorted(FEATURE_REGISTRY.keys())
